// using System;
// using System.Text;

// class MainClass {
//   public static void Main (string[] args) {
//         String  ; //declare as suas variaveis
//         String  ;
//         String  ;

//          = Console.ReadLine(); //insira suas variaveis
//          = Console.ReadLine();
//          = Console.ReadLine();

//       if (( ) && ( )  && ( )) {
//       //complete o desafio
//     }

//      if (( ) && ( )  && ( )) {
//       //complete o desafio
//     }

//      if (( ) && ( )  && ( )) {
//       //complete o desafio
//     }

//      if (( ) && ( )  && ( )) {
//       //complete o desafio
//     }

//      if (( ) && ( )  && ( )) {
//       //complete o desafio
//     }

//      if (( ) && ( )  && ( )) {
//       //complete o desafio
//     }

//     if ((  == "invertebrado") && (  == "anelideo") && ( == "onivoro")) {
//       Console.WriteLine("sanguessuga\n");
//     }


//   }
// }